spring.application.name=CryptoPeak
server.port=8080
spring.profiles.active=dev

#This is the template for the app properties, please add them to your application-dev.properties
#server.error.include-stacktrace=
#spring.jpa.hibernate.ddl-auto=
#spring.datasource.url=jdbc:sqlite:cryptopeak.db
#spring.datasource.driverClassName=org.sqlite.JDBC
#spring.datasource.username=
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#spring.jpa.show-sql=
#jwt-secret=""
#jwt-expiration-ms=
